plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/rake
    - bin/rspec
    - bin/rubocop
    - vendor/**/*
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
