on:
  workflow_call:
jobs:
  docker:
    name: app
    uses: umts/shared-workflows/.github/workflows/docker.yml@main
  rspec:
    name: app
    uses: umts/shared-workflows/.github/workflows/rspec.yml@main
  rubocop:
    name: app
    uses: umts/shared-workflows/.github/workflows/rubocop.yml@main
